services:
  rabbitmq:
    image: rabbitmq:3.13-management
    container_name: rabbitmq_t9
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: appuser
      RABBITMQ_DEFAULT_PASS: apppass