server:
  port: 8081

spring:
  application:
    name: submission
  datasource:
    url: jdbc:h2:mem:submissiondb;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate.format_sql: true
  h2:
    console:
      enabled: true
      path: /h2-console

# 🔹 URL del micro Notification
notification:
  base-url: http://localhost:8080

management:
  endpoints:
    web:
      exposure:
        include: health,info