server:
  port: 8081

spring:
  application:
    name: submission-service

  datasource:
    url: jdbc:h2:mem:submissiondb
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  h2:
    console:
      enabled: true
      path: /h2-console                  # URL: http://localhost:8081/h2-console

  rabbitmq:
    host: localhost
    port: 5672
    username: appuser
    password: apppass
    virtual-host: /

  main:
    allow-bean-definition-overriding: true

app:
  rabbit:
    exchange: thesis.exchange
    queue: thesis.anteproyecto.queue
    routing-key: anteproyecto.createds
